from pathlib import Path

# INPUT VARIABLE
INPUT_FOLDER = Path(r"D:\desk\RawData")


# FLAT VARIABLES
FLAT_SERVES_FOLDER = INPUT_FOLDER / "Flat"                  
FLAT_PIN_POINT_FOLDER = FLAT_SERVES_FOLDER / "Pinpoint"
FLAT_PLATFORM_FOLDER = FLAT_SERVES_FOLDER / "Platform"


# KICK VARIABLES
KICK_SERVES_FOLDER = INPUT_FOLDER / "Kick"
KICK_PIN_POINT_FOLDER = KICK_SERVES_FOLDER / "Pinpoint"
KICK_PLATFORM_FOLDER = KICK_SERVES_FOLDER / "Platform"


# SLICE VARIABLES
SLICE_SERVES_FOLDER = INPUT_FOLDER / "Slice"
SLICE_PIN_POINT_FOLDER = SLICE_SERVES_FOLDER / "Pinpoint"
SLICE_PLATFORM_FOLDER = SLICE_SERVES_FOLDER / "Platform"


# OUTPUT VARIABLES
OUTPUT_FOLDER = Path(r"D:\desk\Results_Mediapipe")
OUTPUT_VIDEOS_FOLDER = OUTPUT_FOLDER / "media_pipe_videos"
OUTPUT_CSVS_FOLDER = OUTPUT_FOLDER / "data_csv"